version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_consents
    environment:
      POSTGRES_DB: consents_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_revoked
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
